packages:
  - .
  - packages/angular_devkit/architect
  - packages/angular_devkit/core
  - packages/angular_devkit/build_webpack
  - packages/angular_devkit/build_angular
  - packages/angular_devkit/schematics
  - packages/angular_devkit/schematics_cli
  - packages/angular/cli
  - packages/angular/pwa
  - packages/angular/ssr
  - packages/angular/build
  - packages/schematics/angular
  - packages/ngtools/webpack
  - modules/testing/builder
  - tests
# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
minimumReleaseAge: 1440
# List of packages to exclude from the minimum release age check.
minimumReleaseAgeExclude:
  - '@angular-devkit/*'
  - '@angular/*'
  - '@ngtools/webpack'
  - '@schematics/*'
  - 'ng-packagr'
overrides:
  '@angular/build': workspace:*
packageExtensions:
  grpc-gcp:
    peerDependencies:
      protobufjs: '*'
  vitest:
    peerDependencies:
      '@vitest/coverage-v8': '*'

engineStrict: true
# Disabling pnpm [hoisting](https://pnpm.io/settings#hoist) by setting `hoist:false` is recommended on
# projects using rules_js so that pnpm outside of Bazel lays out a node_modules tree similar to what
# rules_js lays out under Bazel (without a hidden node_modules/.pnpm/node_modules)
hoist: false

# Avoid pnpm auto-installing peer dependencies. We want to be explicit about our versions used
# for peer dependencies, avoiding potential mismatches. In addition, it ensures we can continue
# to rely on peer dependency placeholders substituted via Bazel.
autoInstallPeers: false

# Avoid prompting for confirmation when pnpm determines node_modules needs to be purged and recreated.
confirmModulesPurge: false

allowBuilds:
  '@firebase/util': false
  '@google/genai': false
  '@parcel/watcher': false
  bufferutil: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  protobufjs: false
  puppeteer: false
  utf-8-validate: false
  webdriver-manager: true
