packages:
  - .
  - packages/angular_devkit/architect
  - packages/angular_devkit/architect_cli
  - packages/angular_devkit/core
  - packages/angular_devkit/build_webpack
  - packages/angular_devkit/build_angular
  - packages/angular_devkit/schematics
  - packages/angular_devkit/schematics_cli
  - packages/angular/cli
  - packages/angular/pwa
  - packages/angular/ssr
  - packages/angular/build
  - packages/schematics/angular
  - packages/ngtools/webpack
  - modules/testing/builder
  - tests
  - tools/baseline_browserslist
# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
minimumReleaseAge: 1440
# List of packages to exclude from the minimum release age check.
# Wildcards are not yet supported: https://github.com/pnpm/pnpm/issues/9983
minimumReleaseAgeExclude:
  - '@angular-devkit/architect'
  - '@angular-devkit/build-angular'
  - '@angular-devkit/build-webpack'
  - '@angular-devkit/core'
  - '@angular-devkit/schematics-cli'
  - '@angular-devkit/schematics'
  - '@angular-devkit/architect-cli'
  - '@angular-devkit/architect'
  - '@angular/animations'
  - '@angular/benchpress'
  - '@angular/cdk'
  - '@angular/ng-dev'
  - '@angular/cli'
  - '@angular/ssr'
  - '@angular/common'
  - '@angular/compiler-cli'
  - '@angular/compiler'
  - '@angular/core'
  - '@angular/forms'
  - '@angular/language-service'
  - '@angular/localize'
  - '@angular/material'
  - '@angular/material-moment-adapter'
  - '@angular/platform-browser-dynamic'
  - '@angular/platform-browser'
  - '@angular/platform-server'
  - '@angular/router'
  - '@angular/service-worker'
  - '@ngtools/webpack'
  - '@schematics/angular'
  - 'ng-packagr'
