packages:
  - .
  - packages/angular_devkit/architect
  - packages/angular_devkit/architect_cli
  - packages/angular_devkit/core
  - packages/angular_devkit/schematics
  - packages/angular/cli
  - packages/angular/pwa
  - packages/schematics/angular
