/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */

import { Command } from '../models/command';
import { Arguments } from '../models/interface';
import { colors } from '../utilities/color';
import { Schema as CompletionSchema } from './completion';
import type { Option } from '../models/interface';

export class CompletionCommand extends Command<CompletionSchema> {
  getCompletionData() {
    const commands = require('../commands.json');
    const commandNames = Object.getOwnPropertyNames(commands);
    const commandOptions = commandNames.map((command) => {
      return require('.' + commands[command]);
    }) as Array<Option>;

    return { commandNames, commandOptions };
  }
  generateFishCompletion(): string {
    let completionString = 'complete -c ng -f -d "The Angular CLI"';
    const { commandNames, commandOptions } = this.getCompletionData();
    commandNames.forEach((command, index) => {
      completionString += `\ncomplete -c ng -n __fish_use_subcommand -a "${command}" -d "${commandOptions[index].description}"`;
    });

    return completionString;
  }
  generateBashCompletion(): string {
    let completionString = '';
    const { commandNames, commandOptions } = this.getCompletionData();
    completionString += `\ncomplete -W "${commandNames.join(' ')}" ng`;

    return completionString;
  }
  async run(options: CompletionSchema & Arguments) {
    if (typeof options.shell === 'undefined') {
      await this.printHelp();

      return;
    }
    switch (options.shell) {
      case 'bash':
        this.logger.info(this.generateBashCompletion());
        break;
      case 'fish':
        this.logger.info(this.generateFishCompletion());
        break;
    }
  }
  public async printHelp() {
    await super.printHelp();
    this.logger.info(
      'Using completions generated by ' +
        colors.cyan('ng completion') +
        ':\n' +
        colors.bold.green('Bash') +
        '\n' +
        colors.yellow('eval "(ng completion -s bash")') +
        '\n',
    );

    return 0;
  }
}
