// Code generated by angular2-stress-test

import { NgModule }       from '@angular/core';
import { BrowserModule  } from '@angular/platform-browser';
import { RouterModule } from '@angular/router'
import { AppComponent }   from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    RouterModule.forRoot([{path: "lazy", loadChildren: "./lazy.module#LazyModule"}])
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
