name: DevInfra

on:
  # zizmor: ignore[dangerous-triggers] - {Trigger is safe as workflow does not checkout untrusted code}
  pull_request_target:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, reopened]

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  labels:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/labeling/pull-request@8d89c9546c88a5487503d603716a6a2ab99fbf0c # main
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
  post_approval_changes:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/post-approval-changes@8d89c9546c88a5487503d603716a6a2ab99fbf0c # main
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
  issue_labels:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/labeling/issue@8d89c9546c88a5487503d603716a6a2ab99fbf0c # main
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
          google-generative-ai-key: ${{ secrets.GOOGLE_GENERATIVE_AI_KEY }}
